spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meal?useSSL=true
    username: root
    password: 123456
server:
  port: 10001
mybatis-plus:
  check-config-location: false
  global-config:
    enable-sql-runner: true
logging:
  level:
    cn.qqhxj: debug
fast-code:
  configPath: config
debug: true