spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meal?useSSL=true
    username: root
    password: 123456
server:
  port: 8080
logging:
  level:
    cn.qqhxj: debug
fast-code:
  configPath: config
